language: node_js
node_js:
- '4'
- '5'
- '6'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script:
- npm test
deploy:
  provider: npm
  email: dancrumb@gmail.com
  on:
    tags: true
    repo: dancrumb/infer-license
  api_key:
    secure: OxlH3u1V5Y/k8Sa4MSLi/QlDdqbn9o1kP11UJPnA8Whmjnts/4OE+VW1NZhyk+wc7/swTn2w8ZSYq47un8XWxUfXml6NLANnu56ooGk6XtTldgJQ7YdJdBruIywwXB+4JQOJfiXWlS3H0rPwRM0fouQxjras46dDWiaujhAilNJdiNZGkDwirjPLz208+1AEVKF9YTdEJEdPhdPL15/zam5iu2Z0vgBT2XQJeeWDHQGFaHpyL3Bw4q0Cv0uGlZFNwKDICHAB0z3G2oXhGFS60cTE7xgOoykOnQCPzWTRkOcmYhriU7hSo2P5JlX50SLXUMJty0wKp9bSOzWQ8YBgVD6GdIAk84O8Mb2xMlHmyfk3tuhR3chGH0Zr3c24a0j1v0gQW80rvqC8P8XPG+sMxCjRdBGPV/4QtKYsd9z/ycMdmM640nc+jaGpolidbPexyoePI7OzBcTph31XBzFzAyJxBowDh/iReaCLZUN1rPBaWxSnsJx+l+7IgRL0Sk+I6HeXMjR/IeEFgoXpAFDB9n15h/YrDXtI+1AQLFrY2j1HYGJhyWrXK8eDLnezE9MwBO5IVF/mpVH7VBmGMw+paP5gQygSxIqNyQtTl+b3STo702/3mk75MmCabETYxhRnXSCOooSQxo8dP6LNWaO2aMgqrJsP7zXZmdXGtGBXxrk=
